In [1]:
import numpy as np
import pandas as pd

In [2]:
# Class6-Data_Manipulation-Module-Week18

# DATA MANIPULATION WEEK-18 ASSIGNMENT

In [ ]:
# 1. Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.
# A vector is a one-dimensional array of lists. 
# A matrix is a two-dimensional data structure where numbers are arranged into rows and columns. 

In [6]:
# 2. 10 elemanli bir listeden NumPy Array’i olusturunuz.
list = [1,2,3,4,5,6,7,8,9,0]
np.array(list)


array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [5]:
# 3. Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.
np.zeros((10,10), dtype = 'int32')


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [8]:
# 4. Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
np.ones((10,10),dtype = 'int32')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [9]:
# 5.	Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.
np.full((10,10),9)


array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [11]:
# 6.	5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

In [12]:
# 7. -1 ile 1 arasinda 30 adet Array olusturunuz.
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [13]:
# 8.	0 ile 30 arasinda 5x6’lik bir matris olusturun.
np.random.randint(0,30,(5,6))

array([[24, 20, 24, 17,  7, 26],
       [18, 17, 23,  9, 21,  4],
       [27, 28, 10,  3, 26, 17],
       [28, 20, 13, 16, 24, 17],
       [ 3,  8,  1, 25,  2,  5]])

In [14]:
# 9.	Kosegenleri 1 olan 10x10’luk bir matris olusturunuz. 
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
# 10. 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
x = np.random.randint(0,10,(5,10))

#* a. eleman sayisini 
print(x.ndim)

#* b. boyut bilgisini/sayisini
print(x.shape)

#* c. satir X sutun bilgisini 
print(x.size)

#* d. veri tipini numpy metodlariyla yazdiriniz.
print(a.dtype)


2
(5, 10)
50
int32


In [18]:
# 11. 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)
np.random.randint(0,10,size = (4,7,3))


array([[[0, 2, 4],
        [3, 7, 1],
        [2, 1, 7],
        [3, 4, 9],
        [1, 7, 2],
        [9, 2, 4],
        [1, 6, 7]],

       [[2, 0, 7],
        [7, 2, 7],
        [8, 3, 7],
        [1, 5, 8],
        [9, 8, 7],
        [8, 9, 3],
        [4, 9, 2]],

       [[0, 5, 8],
        [4, 1, 3],
        [1, 0, 2],
        [1, 7, 1],
        [5, 1, 9],
        [8, 5, 0],
        [1, 7, 0]],

       [[6, 6, 6],
        [7, 7, 4],
        [4, 9, 1],
        [6, 1, 7],
        [9, 2, 1],
        [6, 0, 0],
        [9, 5, 1]]])

In [22]:
# 12. Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)
np.arange(1,10)
np.arange(1,10).reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# 13. 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.
x = np.array([1, 2])
y = np.array([3, 4])
z = np.array([5, 6])
t = np.array([7, 8])

np.concatenate([x,y,z,t])


array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
# 14. 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,
a = np.random.randint(0,10, size = (2,3))
b = np.random.randint(11,20, size = (2,3))
np.concatenate([a,b],axis = 1)

array([[ 9,  6,  1, 17, 13, 15],
       [ 7,  5,  7, 15, 12, 14]])

In [61]:
a = np.arange(0,12).reshape(3,4)
b = np.arange(13,25).reshape(3,4)
np.concatenate([a,b],axis = 1)

array([[ 0,  1,  2,  3, 13, 14, 15, 16],
       [ 4,  5,  6,  7, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 21, 22, 23, 24]])

In [55]:
# 15. Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?


In [47]:
# 16. Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.

In [63]:
# 17. 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.
a = np.arange(0,10)
np.split(a,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [77]:
# 18. Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz. Sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.
b = np.random.randint(0,10,15)
b_s = np.sort(b[::-1])
for i in range (len(b_s)):
    print("index of {} is {}".format(i,b_s[i]))
          

[9 0 9 0 8 5 3 9 4 2 8 5 6 7 3]
[9 2 4 9 6 9 1 0 6 7 4 2 0 0 4]
index of 0 is 0
index of 1 is 0
index of 2 is 2
index of 3 is 3
index of 4 is 3
index of 5 is 4
index of 6 is 5
index of 7 is 5
index of 8 is 6
index of 9 is 7
index of 10 is 8
index of 11 is 8
index of 12 is 9
index of 13 is 9
index of 14 is 9


In [79]:
# 19. 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.
a = np.random.randint(0,20,20)
a[3], a[5], a[7]


(1, 8, 13)

In [82]:
# 20. 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.
x = np.random.randint(0,10,10)
x[4] = 999
x

array([  7,   6,   0,   5, 999,   2,   2,   1,   9,   1])

In [85]:
# 21. “Diagonal Matrix” ve “Trace Matrix” kavramlari hakkinda bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.


In [84]:
# 22. 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [87]:
# 23. 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.
a = np.arange(10,20)
a[3:]

array([13, 14, 15, 16, 17, 18, 19])

In [114]:
# 24. 10X10 luk bir matris olusturunuz ve 3.satirin 5.sutununa ulasiniz. Ayrica;
x = np.random.randint(0,100,100).reshape(10,10)
print(x)

# * a. 5.sutunun tum satirlarina ulasiniz. 
a = x[:,5]
print(a)

# * b. Tum sutunlarin 2.satirlarina ulasiniz. 
b = x[2,:]
print(b)

# * c. tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
c = x[2:7,:]
print(c)

# * d. satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
d = x[2:5,3:7]
print(d)

# * e. satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. 
e = x[5:,:4]
print(e)

# * f. sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
f = x[:,[3,6,9]]
print(f)

# * g. 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.
g = x[5,5] = 1987
print(x)

[[47 96 46 85 45 47 80 98  1 40]
 [69 11 48 65 82 33 19 84 19 96]
 [92 59 72 77 86 18 58 72 76 84]
 [55 74 25 19 19 76 10 82 92 56]
 [ 0 21 77 50 98 32  3 47 50 41]
 [20 88 49 90 80 69 50 24 96 53]
 [15 25 86 76 90 76 64 81 91 15]
 [88 56 72 34 27 16  1 67 73 17]
 [20  2 39 29 90 56 49 86 70 35]
 [42 11 89 78 42 78 33 32 31 66]]
[47 33 18 76 32 69 76 16 56 78]
[92 59 72 77 86 18 58 72 76 84]
[[92 59 72 77 86 18 58 72 76 84]
 [55 74 25 19 19 76 10 82 92 56]
 [ 0 21 77 50 98 32  3 47 50 41]
 [20 88 49 90 80 69 50 24 96 53]
 [15 25 86 76 90 76 64 81 91 15]]
[[77 86 18 58]
 [19 19 76 10]
 [50 98 32  3]]
[[20 88 49 90]
 [15 25 86 76]
 [88 56 72 34]
 [20  2 39 29]
 [42 11 89 78]]
[[85 80 40]
 [65 19 96]
 [77 58 84]
 [19 10 56]
 [50  3 41]
 [90 50 53]
 [76 64 15]
 [34  1 17]
 [29 49 35]
 [78 33 66]]
1987
[[  47   96   46   85   45   47   80   98    1   40]
 [  69   11   48   65   82   33   19   84   19   96]
 [  92   59   72   77   86   18   58   72   76   84]
 [  55   74   25   19   19   76 

In [124]:
# 25. 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz (tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
a = np.arange(0,50,5)

# * a. 20 den buyuk olan kac deger var. 
len(list(filter(lambda x: x>20, a)))

# * b. 30’dan kucuk kac deger var 
len(list(filter(lambda x: x<30, a)))

# * c. icerisinde 33 gecen kac deger var 
len(list(filter(lambda x: x==33, a)))

# * d. olusturulan arrayin tum elemanlarini 5 ile carpin.
a*5

# * e. olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.
a%2


TypeError: 'numpy.ndarray' object is not callable

In [133]:
# 26. 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve ortalamasini aliniz. Ayrica;
x = np.linspace(0,1,50)

# * a. standart sapmasini aliniz. 
print("standard deviation: ",x.std())

# * b. varyansini aliniz.
print("variant: ",x.var())

# * c. median’ini aliniz. 
print("madian: ",np.median(x))

# * d. en kucuk degeri bulunuz. 
print("minimum: ",x.min())

# * e. en buyuk degeri bulunuz.
print("msximum: ",x.max())

standard deviation:  0.2945075446869757
variant:  0.086734693877551
madian:  0.5
minimum:  0.0
msximum:  1.0


In [ ]:
# 27.	Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.


In [135]:
# 28.	Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.
ser = pd.Series(data=np.arange(1,6), index=['A', 'B', 'C', 'D', 'E'])
ser

A    1
B    2
C    3
D    4
E    5
dtype: int32

In [138]:
# 29.	Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. (ornek: fransa:paris)
countries = pd.Series(data=('Istanbul', 'Madrid', 'Amsterdam', 'London', 'Paris'), index=['Turkey','Spain','Netherland','England','France'])
countries

Turkey         Istanbul
Spain            Madrid
Netherland    Amsterdam
England          London
France            Paris
dtype: object

In [139]:
keys = ['Istanbul', 'Madrid', 'Amsterdam', 'London', 'Paris']
values = ['Turkey','Spain','Netherland','England','France']
pd.Series(values,keys)

Istanbul         Turkey
Madrid            Spain
Amsterdam    Netherland
London          England
Paris            France
dtype: object

In [152]:
# 30.	10 elemanli random bir vektor olusturun.
a = np.random.randint(0,10,10)
# * Vektoru seriye cevirip indexleri str olarak belirleyin. 
# (ornek: a,b,c,d,e,f,g.. seklinde)

ser = pd.Series(data=a,index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])

# list("abcdefghij")
# ser = pd.Series(a,list("abcdefghij"))

# * Index ismine gore serinin 3. elemanina ulasin. 
# (ornek: c indexine karsilik gelen deger)
ser['c']

# * Serinin index sirasina gore 1. Elamanina ulasin.
ser['a']

# * Index ismine gore serinin  2. Ve 7. Elemanlarina ayni anda ulasin. 
# (Ornek: b ve g indexine karsilik gelen degerler)
ser[['b','g']]

# * Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin.
# (Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
ser['b':'g']

# * Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.
ser['d':]


d    2
e    3
f    1
g    3
h    8
i    9
j    0
dtype: int32

In [170]:
# 31.	2 adet 5 elemanli seri olusturun.
s1 = pd.Series(range(0,5))
print(s1)
# s2 = pd.Series(list("abcde"))
s2 = pd.Series(['a', 'b', 'c', 'd', 'e'])
print(s2)

# * Olusturdugunuz serileri birlestirin.
s3 = pd.concat([s1,s2])
print(s3)

# * Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
s3.index = range(1,11)
print(s3)

# * Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.
s3.loc[4:6]

s3.iloc[3:7]

0    0
1    1
2    2
3    3
4    4
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object
0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object
1     0
2     1
3     2
4     3
5     4
6     a
7     b
8     c
9     d
10    e
dtype: object


5    4
6    a
7    b
dtype: object

In [172]:
# Master odev ;
# Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz. 
# * Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz. 
# (Matris uretme islemini np.random.random((a,b)) fonksiyonu ile yapabilirsiniz. 0-1 arasi istenen boyutlarda array uretir.)









TypeError: 'list' object is not callable